### ISSUE TITLE
Subir el prototipo a un repo de Github.

### ISSUE THREAD

**Issue by lehysen** [cosola-salvia/proyecto-de-las-plantas#8]
Usando el prototipo que nos mostro la Doctora. 

- [x] Add the files to this repo https://github.com/cosola-salvia/proyecto-plantas-mockups
  - Make sure all links work
- [x] Publish the repo to github pages. This task takes care of #9 
- [x] Add the github pages URL to the project description website url to provide an easy way to get to the page
- [x] Use the `styles.css` file and remove the css module imports

**Comment by misscs** [comment]
Standup

- Please put up what you have now. You can continue work in a branch. We need your intial explorations for the prototyping

**Comment by Morban15** [comment]
Done.

**Comment by misscs** [comment]
Reopening this

- can you put the URL in the website field so we can easily get to it?
<img width="1017" alt="Screen Shot 2020-03-25 at 07 47 27" src="https://user-images.githubusercontent.com/51812/77533289-f8540280-6e6c-11ea-88f3-67fbfe16ec44.png">

**Comment by Morban15** [comment]
![gh-pages](https://user-images.githubusercontent.com/29107510/77618531-e033c000-6f0c-11ea-9a5e-ab98c229ed90.png)

**Comment by misscs** [comment]
[Styles](https://github.com/cosola-salvia/proyecto-plantas-mockups/blob/master/styles/styles.css) are missing

**Comment by Morban15** [comment]
> 
> 
> [Styles](https://github.com/cosola-salvia/proyecto-plantas-mockups/blob/master/styles/styles.css) are missing

**Comment by Morban15** [comment]
Now yes.

**Comment by misscs** [comment]
Looks good! The header is missing and it seems that @cosola never sent the homepage, correct? I will open another ticket. But for now, excellent. another issue done!
