### ISSUE TITLE
Publicarlo en Github pages (o un sub dominio de macile.org)

### ISSUE THREAD

**Issue by lehysen** [cosola-salvia/proyecto-de-las-plantas#9]
- La prueba de la visión del proyecto que nos mostro la Doctora.

**Comment by misscs** [comment]
@lehysen Estamos cerrando esta tarea. Se hará con #8. Gracias por ofrecer tu ayuda.

**Comment by lehysen** [comment]
Entonces unierón el issues 8 con el 9.

**Comment by misscs** [comment]
sí, ya @morban15 se va a hacer carga de terminarlo.

**Comment by Morban15** [comment]
Ya está hecho
